### PR TITLE
Use dependencies.io Lerna support

### PR DESCRIPTION
**Pull request by davegaeddert**
@Hypnosphi and @ndelangen here's an updated `dependencies.yml` that makes use of some new Lerna-specific components. It should be pretty similar to what we discussed.

A couple notes:
- I removed the `repo-issue` actors -- feel free put those back if you want to use them (not sure how you'll want things set up in the end, but we usually suggest minor and patch updates in pull requests, and major updates just as issues)
- You can see that I updated `yarn.lock` here, which was out of date. The js-lerna collector will abort if it notices that it is out of date as-is, which keeps it from going on to send a bunch of pull requests that all have those updates in them in addition to the dependency that they're actually trying to update.
- There does still seem to be a memory-usage issue with the cra-kitchen-sink at least. I'll try and do a little digging to see how much it's trying to use and if there's anything else we can do to make it work, other than just increasing the limits.
- You can look at my fork for examples of pull requests: https://github.com/davegaeddert/storybook/pulls You're more familiar with your repo than I am, so let me know if you see anything out of place.

Here are the repos (which could probably use a little cleanup):
https://github.com/dependencies-io/collector-js-lerna
https://github.com/dependencies-io/actor-js-lerna

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Wow, great work!

In fact, we would like to enable dependencies in [main repo](https://github.com/storybooks/storybook), but we have `yarn.lock` only in `release/3.0` for now. Is there any way to run checkers and actors against a custom branch?

**Comment by davegaeddert** [comment]
@Hypnosphi currently no. I wrote up our last thoughts on that [here](https://github.com/dependencies-io/support/issues/8), which I think I saw you reference somewhere. It's definitely something we want to support, just haven't ironed it out yet.

How would you see it working for your project? Assuming you were to get `dependencies.yml` merged into master eventually, would you have dependencies.io running on master and all of your release branches? Or on master and one of your release branches? Or would it never actually be running against master? Not sure what your workflow is like exactly but if you'd be willing to share a little bit, that would help us answer some lingering questions as to how it would work. I guess the root of the question is: "Which branches do you want pull requests being opened against as updates become available?"

**Comment by Hypnosphi** [comment]
In fact, most of the time we'll need it on `master` only, the current situation is temporary

**Comment by Hypnosphi** [comment]
By the way, how exactly should we keep `yarn.lock` up-to-date? Should running `yarn && yarn bootstrap -- --core` be enough?

**Comment by Hypnosphi** [comment]
We probably also need a separate collector for root `package.json` dependencies, as they aren't handled by lerna

**Comment by davegaeddert** [comment]
> In fact, most of the time we'll need it on master only, the current situation is temporary

@Hypnosphi ok, on the branches we're probably not going to make any immediate changes that would help there. We will be adding in some branch features but right now it just works off whatever is the "default" repo branch.

> By the way, how exactly should we keep yarn.lock up-to-date? Should running yarn && yarn bootstrap -- --core be enough?

Yeah, running yarn (or lerna running yarn) should update the lockfile: https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-managed-by-yarn

Once it is up-to-date and dependencies.io is running, it should basically keep itself up-to-date.

> We probably also need a separate collector for root package.json dependencies, as they aren't handled by lerna
 
That makes sense, but I feel like you could have some weird conflicts with your root `yarn.lock`? Right now it looks like `yarn.lock` has both the root package.json dependencies + all of the hoisted subpackages' dependencies. So if you were to `yarn add twilio` or something in your root, it would regenerate the `yarn.lock` and remove all the subpackages' dependencies since it doesn't know about them (lerna does). Does that make sense? I think that's what is happening in these for example if you look at the diff of `yarn.lock`: https://github.com/Hypnosphi/storybook/pull/2/files

Do you know any other projects that are using Lerna + Yarn + hoisting (`lerna bootstrap --npmClient=yarn --hoist`)? Have you been using it that way for a while? I didn't look too deeply but I think there are some questions around how that combination of stuff is supposed to work, this is one open issue: https://github.com/lerna/lerna/issues/852

Here are some others:
https://github.com/lerna/lerna/search?q=yarn+hoist&type=Issues&utf8=%E2%9C%93

**Comment by davegaeddert** [comment]
You can see the same thing in this new PR from dependencies.io where the hoisted lerna dependencies are being removed from `yarn.lock`: https://github.com/Hypnosphi/storybook/pull/108/files

I guess one solution would be to add a `post_upgrade_command` or something to the `js-npm` actor so that after it ran `yarn upgrade eslint@^4.6.1` (which ruins the `yarn.lock` for lerna) you could have it run your full `yarn bootstrap -- --core` which would fix it back up.

```yaml
- type: js-npm
  path: /
  actors:
  # pull requests for updates to our major version
  - type: js-npm
    versions: "L.Y.Y"
    settings:
      # make sure yarn.lock still includes all lerna+yarn+hoisted dependencies before committing
      post_upgrade_command: yarn bootstrap -- --core
  # create issues for new major versions
  - type: repo-issue
    versions: "Y.0.0"
```

Does that make any sense?

**Comment by ndelangen** [comment]
Considering this:
> So if you were to yarn add twilio or something in your root, it would regenerate the yarn.lock and remove all the subpackages' dependencies since it doesn't know about them (lerna does).

Should we be checking in this `yarn.lock` file?

**Comment by Hypnosphi** [comment]
@ndelangen maybe we should finally try yarn workspaces for bootstrapping phase. In this case `yarn` command would install both root and non-root deps

**Comment by ndelangen** [comment]
Happy to give it a try, but the react-native sections would be a challenge (as they are already)

**Comment by Hypnosphi** [comment]
Well, they are not involved in lerna workflow anyway, so they shouldn't be affected

**Comment by ndelangen** [comment]
Do you want to give it a good, or would you rather have me do it?

**Comment by Hypnosphi** [comment]
I'll give a try

**Comment by Hypnosphi** [comment]
Here it is https://github.com/storybooks/storybook/pull/1810

**Comment by davegaeddert** [comment]
I'm guessing you guys probably saw Yarn 1.0 hit stable today: https://code.facebook.com/posts/274518539716230

We've updated all our js components to use it. Let me know if you have any questions about testing out your new setup.

**Comment by ndelangen** [comment]
I'm experimenting with it right now 👍

**Comment by davegaeddert** [comment]
I was just checking in on this and taking a look at the error: `error storybook@3.0.0: The engine "node" is incompatible with this module. Expected version "node".`

Is there a reason that this is set this way? 
https://github.com/Hypnosphi/storybook/blob/93c4a84ae8a537563b2208f863618b74d6d9109b/package.json#L82-L84

**Comment by davegaeddert** [comment]
@Hypnosphi @ndelangen does it look like this is going to work?

**Comment by Hypnosphi** [comment]
@davegaeddert definitely so!

**Comment by davegaeddert** [comment]
Great! Let me know if you have any other questions, otherwise I'll stop bugging you for a little while!

**Comment by Hypnosphi** [comment]
Actually, I have one: after introducing yarn workspaces, root dependencies are installed along with ones of packages (with `yarn` command). Does it mean that we can somehow merge root `js-npm` task with `js-lerna`?

**Comment by davegaeddert** [comment]
@Hypnosphi take a look at https://github.com/Hypnosphi/storybook/pull/143

**Pull request merged**
